dnnlib: Running run_generator.generate_images() on localhost...
Loading networks from "gdrive:networks/stylegan2-ffhq-config-f.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Failed!
Traceback (most recent call last):
  File "c:/dev/forks/stylegan2/run_generator.py", line 168, in <module>
    main()
  File "c:/dev/forks/stylegan2/run_generator.py", line 163, in main
    dnnlib.submit_run(sc, func_name_map[subcmd], **kwargs)
  File "c:\dev\forks\stylegan2\dnnlib\submission\submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "c:\dev\forks\stylegan2\dnnlib\submission\internal\local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "c:\dev\forks\stylegan2\dnnlib\submission\submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "c:\dev\forks\stylegan2\run_generator.py", line 21, in generate_images
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "c:\dev\forks\stylegan2\pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
  File "c:\dev\forks\stylegan2\dnnlib\tflib\network.py", line 297, in __setstate__
    self._init_graph()
  File "c:\dev\forks\stylegan2\dnnlib\tflib\network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "c:\dev\forks\stylegan2\dnnlib\tflib\ops\fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "c:\dev\forks\stylegan2\dnnlib\tflib\ops\fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "c:\dev\forks\stylegan2\dnnlib\tflib\ops\fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "c:\dev\forks\stylegan2\dnnlib\tflib\custom_ops.py", line 112, in get_plugin
    _run_cmd(_prepare_nvcc_cli('"%s" --preprocess -o "%s" --keep --keep-dir "%s"' % (cuda_file, tmp_file, tmp_dir)))
  File "c:\dev\forks\stylegan2\dnnlib\tflib\custom_ops.py", line 62, in _run_cmd
    raise RuntimeError('NVCC returned an error. See below for full command line and output log:\n\n%s\n\n%s' % (cmd, output))
RuntimeError: NVCC returned an error. See below for full command line and output log:

nvcc "c:\dev\forks\stylegan2\dnnlib\tflib\ops\fused_bias_act.cu" --preprocess -o "C:\Users\ADMINI~2\AppData\Local\Temp\tmpklpv1b5s\fused_bias_act_tmp.cu" --keep --keep-dir "C:\Users\ADMINI~2\AppData\Local\Temp\tmpklpv1b5s" --disable-warnings --include-path "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\include" --include-path "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\include\external\protobuf_archive\src" --include-path "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\include\external\com_google_absl" --include-path "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\tensorflow\include\external\eigen_archive" --compiler-bindir "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64" 2>&1

'nvcc' is not recognized as an internal or external command,
operable program or batch file.

